/*****************************************************************************/
/*         (c) Copyright, Real-Time Innovations, All rights reserved.        */
/*                                                                           */
/*         Permission to modify and use for internal purposes granted.       */
/* This software is provided "as is", without warranty, express or implied.  */
/*                                                                           */
/*****************************************************************************/

/* --- Time type: ------------------------------------------------------- */

/*
 * This is the Time type.
 *
 * Description < >
 *
 */
struct Time {
        /*
         * Description < >
         */
        unsigned long sec;

        /*
         * Description < >
         */
        unsigned long nsec;
};

/* --- Header type: ------------------------------------------------------- */

/*
 * This is the Header type.
 *
 * Description < >
 *
 */
struct Header {
        /*
         * Description < >
         */
        Time stamp;

        /*
         * Description < >
         */
        string frame_id;

};

/* --- position type: ------------------------------------------------------- */

/*
 * This is the Position type.
 *
 * Description < >
 *
 */
struct Position {
        /*
         * Description < >
         */
         float x;

        /*
         * Description < >
         */
        float y;

        /*
         * Description < >
         */
        float z;

};

/* --- Orientation type: ------------------------------------------------------- */

/*
 * This is the Orientation type.
 *
 * Description < >
 *
 */
struct Orientation {
        /*
         * Description < >
         */
         float x;

        /*
         * Description < >
         */
        float y;

        /*
         * Description < >
         */
        float z;

        /*
         * Description < >
         */
        float w;

};

/* --- World_Pose type: ------------------------------------------------------- */

/*
 * This is the World_Pose type.
 *
 * Description < >
 *
 */
struct World_Pose {
        /*
         * Description < >
         */
        Position position;

        /*
         * Description < >
         */
        Orientation orientation;

};



/* --- laser_Scan_msg type: ------------------------------------------------------- */

/*
 * This is the laser_Scan_msg type.
 *
 * Description < >
 *
 */
struct laser_Scan_msg {
        /*
         * Description < >
         */
        long   laser_id; //@key

        /*
         * Description < >
         */
        Header   header;

        /*
         * Description < >
         */
        World_Pose   world_pose;

        /*
         * Description < >
         */
        float   angle_min;

        /*
         * Description < >
         */
        float   angle_max;

        /*
         * Description < >
         */
        float   angle_step;

        /*
         * Description < >
         */
        float   range_min;

        /*
         * Description < >
         */
        float   range_max;

        /*
         * Description < >
         */
        long   count;

                /*
         * Description < >
         */
        float   vertical_angle_min;

        /*
         * Description < >
         */
        float   vertical_angle_max;

        /*
         * Description < >
         */
        float   vertical_angle_step;

        /*
         * Description < >
         */
        float   vertical_count;

        /*
         * Description < >
         */
        sequence<float>   ranges;

        /*
         * Description < >
         */
        sequence<float>   intensities;
};
